### ISSUE TITLE
hookspec UserWarning on use

### ISSUE THREAD

**Issue by divad** [freakboy3742/pytest-tldr#11]
I tried out using pytest-tldr on Python 3.7 and it worked, but produced an odd warning:

`/usr/local/lib/python3.7/site-packages/pytest_tldr.py:282: UserWarning: Argument(s) ('config',) which are declared in the hookspec can not be found in this hook call
terminalreporter=self, exitstatus=exitstatus`

Is this a bug?

**Comment by freakboy3742** [comment]
Sounds like it might be. I can't say I've seen this message myself, though, so there's probably some sort of interaction with another pytest plugin that is causing it.

Can you narrow down the minimum environment configuration and test case that causes this message to be raised?

**Comment by fbarbu15** [comment]
Same issue here:
c:\work_dir\cop_regression\lib\site-packages\pytest_tldr.py:282: UserWarning: Argument(s) ('config',) which are declared in the hookspec can not be found in this hook call
  terminalreporter=self, exitstatus=exitstatus
ok

**Comment by freakboy3742** [comment]
@fbarbu15 Same response - can you narrow down the minimum environment where you see this error?

**Comment by freakboy3742** [comment]
I've found the problem - PyTest 4.2 introduced an extra argument requirement to `pytest_terminal_summary`. Fix incoming shortly.
