### ISSUE TITLE
Enable TLDR with a flag?

### ISSUE THREAD

**Issue by countvajhula** [freakboy3742/pytest-tldr#17]
Hi there,
This is a great plugin! Is there a way to either enable the plugin with a flag (e.g. `pytest --tldr`) or alternatively disable it with a flag (e.g. `pytest --no-tldr`) while it is installed?

It would be nice to have the option to look at the TLDR output during test development, and complete (e.g. native pytest, or even `pytest-sugar` or `pytest-cov`) output in other cases such as in a CI dashboard, as sometimes the additional context there in the default/sugared output is helpful.

Ideally in order to play nicely with other plugins that may be installed, it would be great if config could be specified in `setup.cfg` to indicate whether TLDR should be enabled or disabled in a default `pytest` invocation, and then the flags `--tldr` and `--no-tldr` could toggle it at runtime, depending on the default value.

**Comment by freakboy3742** [comment]
It turns out PyTest already has a flag for this. The `-p` flag can be used to disable any plugin -- 
```
$ pytest -p no:tldr
```
will run pytest, but without tldr installed. This works for *any* plugin - not just tldr; you just need to specify the name that is registered with pytest. 

Is that enough for your purposes? Or do you think a tldr-specific flag is still required?

**Comment by countvajhula** [comment]
That sounds almost perfect! But it still means that running pytest in different settings should always be aware of the possible existence of the TLDR plugin. E.g. in my `Makefile` I currently have different targets for running unit tests, functional tests, tests with debugging enabled, and so on. I'd like to add a similar target for TLDR test output. If a plugin-specific flag were available with a default configurable in `setup.cfg`, then this could be accomplished easily, by just adding the single extra target for tldr (and setting the default value to `False` in setup.cfg). On the other hand, using the pytest plugin-agnostic option means that every one of the other pytest-related targets would need to be modified to include `-p no:tldr`. So it still seems desirable, even if not essential to achieve the stated goal. WDYT?

**Comment by countvajhula** [comment]
Hmm, looks like the `-p no:tldr` option can be set [globally](https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-name) in `setup.cfg`, so that would solve the problem of it being disabled by default. Now, if only there were a way to _enable_ a specific plugin at the command line invocation of pytest...

**Comment by countvajhula** [comment]
Ok, I think a viable option to do it this way is by disabling plugin autoloading in pytest and then enabling each plugin explicitly. Noting down how this is done in case it's helpful to anyone else:

First set the environment variable in the appropriate place, e.g.:
`export PYTEST_DISABLE_PLUGIN_AUTOLOAD=1`
or if in a `Makefile` just set it at the top:
`PYTEST_DISABLE_PLUGIN_AUTOLOAD=1`

Once the environment variable is set:

- Running pytest with TLDR:
` pytest -p tldr`

- Running pytest with no plugins:
`pytest`

- Running pytest with many plugins:
`pytest -p <plugin-1> -p <plugin-2> ...`

In any case, looks like this is a pytest-wide usage pattern and not plugin specific. Am closing this issue, thanks for the quick response!
