### ISSUE TITLE
print calls should always use report.longreprtext

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [freakboy3742/pytest-tldr#26]
due to https://github.com/freakboy3742/pytest-tldr/blob/master/pytest_tldr.py#L303
we received https://github.com/pytest-dev/pytest/issues/7626

i believe the best solution to prevent that in future is to either use `longreprtext` instead of `longrepr` for printing or to use `totermainal` where applicable

**Comment by freakboy3742** [comment]
Thanks for the report! This does indeed looks like a bug that has been exposed by the release of pytest 6. I should have a fix shortly.
