### ISSUE TITLE
No write to terminal, 

### ISSUE THREAD

**Issue by rixx** [freakboy3742/pytest-tldr#28]
With pytest-tldr==0.2.2 and pytest==6.0.1, I'm seeing behaviour that turns up no output in the terminal at all, until either the tests are completed or I abort the test process – then, all collected output is printed at once. (FWIW, this doesn't happen with pytest-sugar)

**Comment by freakboy3742** [comment]
Thanks for the report. I'm guessing this is related to the pytest compatibility checks from #27, and an output buffer not being flushed.
