### ISSUE TITLE
Suppresses Collection Errors

### ISSUE THREAD

**Issue by sagarchalise** [freakboy3742/pytest-tldr#5]
When there is an error in Test Collections such as `SyntaxError`, it would be nice to be reminded of that.

Basically, shows

```
----------------------------------------------------------------------
Ran 0 tests

OK
```

when running pytest with syntax error code such as `print 'hello'` in python3.

**Comment by freakboy3742** [comment]
Thanks for the report; I noticed this myself during some testing yesterday.
